//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraigslistJobApplier.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public string Email1 { get; set; }
        public string MessageSubject { get; set; }
        public string Location { get; set; }
        public Nullable<bool> HasBeenSent { get; set; }
    }
}
